install.packages("biostrings")
if (!requireNamespace("BiocManager", quietly = TRUE))
  install.packages("BiocManager")
BiocManager::install("Biostrings")
library("msa")
library(BiocGenerics)
library(BiocManager)
library(Biostrings)
library("msa")

if

Corynebacterium<-readAAStringSet("C:/Users/nat_g/OneDrive/Escritorio/Bioinfo/Archivo de secuencias2.txt")
Corynebacterium
letterFrequency(Corynebacterium,"A")
letterFrequency(Corynebacterium, "D")
letterFrequency(Corynobacterium, "E")
letterFrequency(Corynebacterium, "E")
letterFrequency(Corynebacterium, "R")
letterFrequency(Corynebacterium, "K")
letterFrequency(Corynebacterium, "N")
letterFrequency(Corynebacterium, "H")
letterFrequency(Corynebacterium, "Q")
letterFrequency(Corynebacterium, "S")
letterFrequency(Corynebacterium, "T")
letterFrequency(Corynebacterium, "G")
letterFrequency(Corynebacterium, "V")
letterFrequency(Corynebacterium, "P")
letterFrequency(Corynebacterium, "L")
letterFrequency(Corynebacterium, "F")
letterFrequency(Corynebacterium, "Y")
letterFrequency(Corynebacterium, "I")
letterFrequency(Corynebacterium, "M")
letterFrequency(Corynebacterium, "W")
letterFrequency(Corynebacterium, "C")

A<-letterFrequency(Corynebacterium,"A")
A
D<-letterFrequency(Corynebacterium, "D")
E<-letterFrequency(Corynebacterium, "E")
R<-letterFrequency(Corynebacterium, "R")
K<-letterFrequency(Corynebacterium, "K")
N<-letterFrequency(Corynebacterium, "N")
H<-letterFrequency(Corynebacterium, "H")
Q<-letterFrequency(Corynebacterium, "Q")
S<-letterFrequency(Corynebacterium, "S")
Tr<-letterFrequency(Corynebacterium, "T")
G<-letterFrequency(Corynebacterium, "G")
V<-letterFrequency(Corynebacterium, "V")
P<-letterFrequency(Corynebacterium, "P")
L<-letterFrequency(Corynebacterium, "L")
Fe<-letterFrequency(Corynebacterium, "F")
Y<-letterFrequency(Corynebacterium, "Y")
I<-letterFrequency(Corynebacterium, "I")
M<-letterFrequency(Corynebacterium, "M")
W<-letterFrequency(Corynebacterium, "W")
C<-letterFrequency(Corynebacterium, "C")
library("plyr")
install.packages("plyr")
barplot("A")
barplot(A)
A
barplot(A, main = "Frequencia de Alanina",
        col = rainbow(3))
barplot(A, main = "Frequencia de Alanina",
        col = aquamarine)
hist(A, main = "Frequencia de Alanina",
     col = aquamarine)
hist(A, main = "Frequencia de Alanina",
     col = rainbow(3))
A
boxplot.default(A, main = "Frequencia de Alanina",
                col = rainbow(3))
boxplot(A, main = "Frequencia de Alanina",
        col = rainbow(3))
plot(A, main = "Frequencia de Alanina",
     col = rainbow(3))
Sq1<-as.character(Corynebacterium[[1]])
sq2<-as.character(Corynebacterium[[2]])
PairwiseAlignments(pattern = sq2, subject = Sq1)
